begin;

alter table public.video_categories rename to categories;
alter table public.video_tags rename to tags;

create table public.category_groups (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  sort_order integer not null default 0,
  created_at timestamp with time zone not null default timezone('utc'::text, now()),
  updated_at timestamp with time zone not null default timezone('utc'::text, now())
);

create table public.tag_groups (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  sort_order integer not null default 0,
  created_at timestamp with time zone not null default timezone('utc'::text, now()),
  updated_at timestamp with time zone not null default timezone('utc'::text, now())
);

alter table public.category_groups enable row level security;
alter table public.tag_groups enable row level security;

insert into public.category_groups (slug, name, sort_order)
select distinct
  categories.group_key as slug,
  case categories.group_key
    when 'region' then '地区'
    when 'content_type' then '内容类型'
    when 'production' then '制作方式'
    else categories.group_key
  end as name,
  case categories.group_key
    when 'region' then 10
    when 'content_type' then 20
    when 'production' then 30
    else 999
  end as sort_order
from public.categories
order by sort_order, slug;

insert into public.tag_groups (slug, name, sort_order)
select distinct
  tags.group_key as slug,
  case tags.group_key
    when 'scene' then '场景'
    when 'mood' then '氛围'
    when 'duration' then '时长'
    when 'format' then '画面格式'
    when 'language' then '语言'
    when 'editorial' then '编辑推荐'
    else tags.group_key
  end as name,
  case tags.group_key
    when 'scene' then 10
    when 'mood' then 20
    when 'duration' then 30
    when 'format' then 40
    when 'language' then 50
    when 'editorial' then 60
    else 999
  end as sort_order
from public.tags
order by sort_order, slug;

alter table public.categories add column group_id bigint;
alter table public.tags add column group_id bigint;

update public.categories
set group_id = category_groups.id
from public.category_groups
where category_groups.slug = categories.group_key;

update public.tags
set group_id = tag_groups.id
from public.tag_groups
where tag_groups.slug = tags.group_key;

alter table public.categories drop constraint if exists video_categories_name_key;
alter table public.tags drop constraint if exists video_tags_name_key;

alter table public.categories
  rename constraint video_categories_pkey to categories_pkey;
alter table public.categories
  rename constraint video_categories_slug_key to categories_slug_key;
alter table public.tags
  rename constraint video_tags_pkey to tags_pkey;
alter table public.tags
  rename constraint video_tags_slug_key to tags_slug_key;

drop index if exists public.video_categories_group_sort_idx;
drop index if exists public.video_tags_group_sort_idx;

alter table public.categories
  add constraint categories_group_id_fkey
  foreign key (group_id) references public.category_groups(id) on delete restrict;
alter table public.tags
  add constraint tags_group_id_fkey
  foreign key (group_id) references public.tag_groups(id) on delete restrict;

alter table public.categories
  alter column group_id set not null;
alter table public.tags
  alter column group_id set not null;

alter table public.categories
  add constraint categories_group_id_name_key unique (group_id, name);
alter table public.tags
  add constraint tags_group_id_name_key unique (group_id, name);

create index category_groups_sort_idx on public.category_groups (sort_order, id);
create index tag_groups_sort_idx on public.tag_groups (sort_order, id);
create index categories_group_id_sort_idx on public.categories (group_id, sort_order, id);
create index tags_group_id_sort_idx on public.tags (group_id, sort_order, id);

alter table public.categories drop column group_key;
alter table public.tags drop column group_key;

commit;
